In [1]:
#Artificial Neural Network
#Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

In [4]:
#Part 1 - Data Preprocessing
#Importing the dataset
df = pd.read_csv("./hotel_data.csv")

In [5]:
df.head()

Rows  CustomerId   Surname  Points       Branch  Gender  Age  Years  \
0     1    15774401    Sharma     773        Delhi    Male   51      4   
1     2    15585768     Singh     582    Bangalore    Male   41      6   
2     3    15793856  Kulkarni     667        Delhi  Female   36      3   
3     4    15723721     Sayed     543  Maharashtra    Male   30      4   
4     5    15690330  Gavaskar     830    Bangalore  Female   40      8   

   SpentAmount  NumOfItems  OnlinePayment  OnlineOrders  EstimatedSalary  \
0         0.00           2              0             0        123587.83   
1     70349.48           2              0             1        178074.04   
2    121542.57           2              1             1        186841.71   
3    140916.81           1              1             0        157711.18   
4     77701.64           1              0             1         19512.38   

   Regular  
0        0  
1        1  
2        1  
3        1  
4        1

In [6]:

X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1]

In [7]:
print(X)

[[773 'Delhi' 'Male' ... 0 0 123587.83]
 [582 'Bangalore' 'Male' ... 0 1 178074.04]
 [667 'Delhi' 'Female' ... 1 1 186841.71]
 ...
 [753 'Maharashtra' 'Male' ... 0 1 195563.99]
 [536 'Maharashtra' 'Male' ... 1 0 61094.53]
 [631 'Bangalore' 'Female' ... 1 1 31613.35]]


In [8]:
print(y)

0       0
1       1
2       1
3       1
4       1
       ..
9995    1
9996    0
9997    1
9998    1
9999    1
Name: Regular, Length: 10000, dtype: int64


In [10]:
#Encoding categorical data
#Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [11]:
#One Hot Encoding the "Branch" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[0.0 1.0 0.0 ... 0 0 123587.83]
 [1.0 0.0 0.0 ... 0 1 178074.04]
 [0.0 1.0 0.0 ... 1 1 186841.71]
 ...
 [0.0 0.0 1.0 ... 0 1 195563.99]
 [0.0 0.0 1.0 ... 1 0 61094.53]
 [1.0 0.0 0.0 ... 1 1 31613.35]]


In [13]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
X_train

array([[-0.57908232, -0.57504086,  0.99925028, ...,  0.64162424,
         0.96704278,  1.36969934],
       [-0.57908232, -0.57504086,  0.99925028, ...,  0.64162424,
         0.96704278, -0.7534562 ],
       [-0.57908232, -0.57504086,  0.99925028, ..., -1.55854461,
        -1.03408041, -0.28998627],
       ...,
       [ 1.72687019, -0.57504086, -1.00075028, ...,  0.64162424,
        -1.03408041,  0.69783154],
       [-0.57908232, -0.57504086,  0.99925028, ...,  0.64162424,
        -1.03408041,  1.36002245],
       [ 1.72687019, -0.57504086, -1.00075028, ...,  0.64162424,
        -1.03408041,  1.34525275]])

In [16]:

X_test

array([[-0.57908232, -0.57504086,  0.99925028, ...,  0.64162424,
         0.96704278, -0.7181826 ],
       [-0.57908232,  1.73900686, -1.00075028, ...,  0.64162424,
         0.96704278, -1.58146288],
       [-0.57908232, -0.57504086,  0.99925028, ..., -1.55854461,
        -1.03408041,  0.14936664],
       ...,
       [ 1.72687019, -0.57504086, -1.00075028, ...,  0.64162424,
         0.96704278,  1.7302574 ],
       [-0.57908232, -0.57504086,  0.99925028, ...,  0.64162424,
        -1.03408041,  1.53016353],
       [-0.57908232,  1.73900686, -1.00075028, ..., -1.55854461,
        -1.03408041,  1.67623577]])

In [17]:
#Part 2 - Building the ANN.
#It is like building an artificial brain!

#Initializing the ANN
#As a sequence of layers
ann = tf.keras.models.Sequential()

In [18]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [19]:
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [20]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [21]:
#Part 3 - Training the ANN
#Compiling the ANN
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [22]:
#Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100


250/250 [==============================] - 3s 3ms/step - loss: 0.5653 - accuracy: 0.7850
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4739 - accuracy: 0.7958
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4467 - accuracy: 0.8008
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4334 - accuracy: 0.8094
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4257 - accuracy: 0.8149
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4185 - accuracy: 0.8207
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4103 - accuracy: 0.8270
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4005 - accuracy: 0.8338
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3903 - accuracy: 0.8391
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3800 - accu

In [23]:
#Part 4 - Making the predictions and evaluating the model
#Predicting the Test set results
y_pred = ann.predict(X_test)

63/63 [==============================] - 0s 2ms/step


In [24]:

y_pred

array([[0.9937255 ],
       [0.85761863],
       [0.79487073],
       ...,
       [0.6588604 ],
       [0.7307674 ],
       [0.86753005]], dtype=float32)

In [25]:
y_pred = (y_pred > 0.5)

In [26]:
y_pred

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [27]:
y_pred = np.array(y_pred, dtype=int)

In [28]:
y_pred

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [29]:
#Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 176  227]
 [  77 1520]]


0.848